DROP DATABASE IF EXISTS BAMAZON;

CREATE DATABASE BAMAZON;

USE BAMAZON;

CREATE TABLE PRODUCTS(
    ITEM_ID INTEGER(10) AUTO_INCREMENT NOT NULL,
    PRODUCT_NAME VARCHAR(100),
    DEPARTMENT_NAME VARCHAR(100),
    PRICE INTEGER(10),
    STOCK_QUANTITY INTEGER(10),
    PRIMARY KEY(ITEM_ID)
);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Dove", "Cosmetics", 30.00, 30);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Carrot", "Grocery", 2.00, 100);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Pantene", "Hair Care", 12.00, 200);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Palak Greens", "Grocery", 1.00, 100);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Beans", "Grocery", 5.00, 1000);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Mac", "Cosmetics", 45.00, 50);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Maybelline", "Cosmetics", 42.00, 25);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Lakme", "Cosmetics", 40.00, 22);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Okra", "Grocery", 3.40, 100);

INSERT INTO PRODUCTS(PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES("Avacado", "Grocery", 1.54, 100);